<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>DSAN6000 Group 14 - Exploratory Data Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">DSAN 6000 Group 14</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="./introduction.html">
      <span class="menu-text">Introduction</span></a>
    </li>
  <li class="nav-item">
    <a class="nav-link active" href="./eda.html" aria-current="page">
 <span class="menu-text">EDA</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./nlp.html">
 <span class="menu-text">NLP</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./ml.html">
 <span class="menu-text">ML</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./conclusion.html">
 <span class="menu-text">Conclusion</span></a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" href="./feedback.html">
 <span class="menu-text">Feedback</span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
<!-- margin-sidebar -->
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
<h2 id="toc-title">Contents</h2>

<ul>
<li><a href="#executive-summary" id="executive summary" class="nav-link" data-scroll-target="#data-information-and-introduction">Executive Summary</a></li>
<li><a href="#EDA-1" id="EDA 1" class="nav-link" data-scroll-target="#data-information-and-introduction">Research on user activity in iphone community</a></li>
<li><a href="#EDA-2" id="EDA 2" class="nav-link" data-scroll-target="#data-cleaning">Research on posts in iphone community</a></li>
<li><a href="#EDA-3" id="EDA 3" class="nav-link" data-scroll-target="#dataset-overview">Reddit Impact Analysis</a></li>
</ul>
</nav>
</div>

<!-- main -->
<main class="content" id="quarto-document-content">



<section id="Exploratory Data Analysis" class="level1">
<h1>Reddit Community Dynamics and Influence Analysis (EDA)</h1>

<p><a href="../website/poster_portrait_analysis.html">Note:Link to the source code of EDA 1</a></p>
<p><a href="../website/popular_posts_analysis.html">Note:Link to the source code of EDA 2</a></p>
<p><a href="../website/reddit_impact_analysis.html">Note:Link to the source code of EDA 3</a></p>

<section id="executive-summary" class="level2">
  <h2 class="anchored" data-anchor-id="Executive-Summary">Executive Summary</h2>
          <p>
            The exploration begins with a deep dive into the community dynamics and influence within Reddit. We aim to dissect the patterns that define user engagement and influence the discourse within Apple-centric subreddits. Our Reddit Impact Analysis sought to understand and identify elements with substantial influence across different communities. By employing metrics such as the number of comments, score, and discussion duration, we gained a nuanced understanding of content impact, ranging from instant popularity to lasting influence. These accomplishments collectively contribute to a more profound understanding of user engagement, community dynamics, and influential factors on the Reddit platform, aligning with our overarching goal of providing strategic insights for community enhancement and business decision-making.

          </p>
          
</section>


<section id="EDA-1" class="level2">
<h2 class="anchored" data-anchor-id="EDA-1">Research on user activity in iphone community (EDA 1)</h2>
<p><strong>A Reminder for Our Business Goal:</strong>Conducting user activity research in the iphone subreddit is critical to understanding community dynamics, especially how important product launches like the iPhone 14 impact user engagement. This research benefits community managers, marketers, and product developers by revealing user interaction patterns and identifying key influencers. These insights can effectively inform marketing strategies, product development and customer engagement approaches.</p>
<p><strong>Analysis:</strong>  
        <p>
          Understanding user engagement in online communities, especially surrounding key events like product launches, is essential. This chart depicts the activity levels of iPhone subreddit users from March to July 2022, a period before the iPhone 14 release. It serves to illustrate the impact of such events on user behavior. By analyzing posting and commenting patterns quantified through a specific activity formula, we can observe the distribution of top contributors' engagement, providing actionable insights for community managers, marketers, and product developers as they strategize for post-launch activities.
        </p>
				<iframe src="../website/eda1_1.html" width="800" height="600"></iframe>
        <p>
          This dynamic diagram is the top 15 users were active from March to July.
        </p>
        <p>
          The selection of the top 15 most active contributors for analysis is based on the principles of the Pareto 80/20 rule[Referenced the information provided by AI], where a small number of contributors (in this case the top 15) are expected to account for activity and influence within the Reddit subreddit A large part of the force. This focused approach enables more manageable and targeted analysis, resulting in clearer patterns and actionable findings. From the figure we can see, except for two prominent contributors, the main contributors on the iPhone subreddit from March to July (that is, between the iPhone 13 and iPhone 14 release cycles) have a relatively even distribution of activity. This suggests that during the lull after the iPhone 13 launch and before the iPhone 14 launch, relatively balanced activity reflected a broader range of topics, with no single contributor dominating the narrative and a diverse community of discussions. And this kind of diversified participation helps determine users' interest in general iPhone products, helps readers and users obtain a wide range of suggestions, and also helps Apple to adopt opinions.
        </p>
        <iframe src="../website/eda1_2.html" width="800" height="600"></iframe>
        <p>
          This dynamic diagram is the top 15 users were active from August to December. 
        </p>
        <p>
          After the iPhone 14 launch, the subreddit's contributor dynamics shifted significantly. First of all, the activity of active contributors has been greatly improved. Secondly, a very obvious "leader" has emerged. There are three contributors with very large contributions, and the other contributors are in a relatively balanced state. The presence of three highly active contributors may indicate that a small group of users drives most discussions. This change may result in a single discussion environment where specific topics or perspectives become more visible under the influence of these dominant voices. However, this centralized discussion mode helps readers and users find iPhone14 information more quickly and efficiently. It also helps Apple to grasp public opinion trends in a timely manner and adjust its market and product strategies.
        </p>
        <p>
          Later, in order to understand whether the contributors in these two time periods overlapped and to explore the contributor pattern in the iPhone community, we marked the user names that were repeatedly listed in the two time periods.
        </p>
        <table class="dataframe table table-sm table-striped">
          <thead>
              <tr>
                  <th>Author</th>
                  <th>Repeat Time</th>
                  <th>3-7 Activity</th>
                  <th>8-12 Activity</th>
              </tr>
          </thead>
          <tbody>
              <tr>
                  <td>Simon_787</td>
                  <td>2</td>
                  <td>430</td>
                  <td>856</td>
              </tr>
              <tr>
                  <td>Pantheon73</td>
                  <td>2</td>
                  <td>182</td>
                  <td>247</td>
              </tr>
              <tr>
                  <td>JohnFlufin</td>
                  <td>2</td>
                  <td>162</td>
                  <td>559</td>
              </tr>
              <tr>
                  <td>3dforlife</td>
                  <td>2</td>
                  <td>102</td>
                  <td>123</td>
              </tr>
              <tr>
                  <td>D_Empire412</td>
                  <td>2</td>
                  <td>112</td>
                  <td>180</td>
              </tr>
              <tr>
                  <td>PJ09</td>
                  <td>1</td>
                  <td>243</td>
                  <td>0</td>
              </tr>
              <tr>
                  <td>WahidUmmah4312</td>
                  <td>1</td>
                  <td>244</td>
                  <td>0</td>
              </tr>
              <tr>
                  <td>katsumiblisk</td>
                  <td>1</td>
                  <td>460</td>
                  <td>0</td>
              </tr>
              <tr>
                  <td>zerbey</td>
                  <td>1</td>
                  <td>245</td>
                  <td>0</td>
              </tr>
              <tr>
                  <td>iphone14vn</td>
                  <td>1</td>
                  <td>225</td>
                  <td>0</td>
              </tr>
              <tr>
                  <td>Wallaceb3878</td>
                  <td>1</td>
                  <td>189</td>
                  <td>0</td>
              </tr>
              <tr>
                  <td>keffordman</td>
                  <td>1</td>
                  <td>116</td>
                  <td>0</td>
              </tr>
              <tr>
                  <td>Allowmancer</td>
                  <td>1</td>
                  <td>161</td>
                  <td>0</td>
              </tr>
              <tr>
                  <td>NickyGi</td>
                  <td>1</td>
                  <td>113</td>
                  <td>0</td>
              </tr>
              <tr>
                  <td>iphone12case</td>
                  <td>1</td>
                  <td>110</td>
                  <td>0</td>
              </tr>
              <tr>
                  <td>dislikebuttonz</td>
                  <td>1</td>
                  <td>0</td>
                  <td>716</td>
              </tr>
              <tr>
                  <td>Golfswingfore24</td>
                  <td>1</td>
                  <td>0</td>
                  <td>191</td>
              </tr>
              <tr>
                  <td>JaxTellerr</td>
                  <td>1</td>
                  <td>0</td>
                  <td>147</td>
              </tr>
              <tr>
                  <td>paulrudder</td>
                  <td>1</td>
                  <td>0</td>
                  <td>123</td>
              </tr>
              <tr>
                  <td>owtlowd</td>
                  <td>1</td>
                  <td>0</td>
                  <td>115</td>
              </tr>
              <tr>
                  <td>antdude</td>
                  <td>1</td>
                  <td>0</td>
                  <td>112</td>
              </tr>
              <tr>
                  <td>Administratr</td>
                  <td>1</td>
                  <td>0</td>
                  <td>111</td>
              </tr>
              <tr>
                  <td>abdallahzeid</td>
                  <td>1</td>
                  <td>0</td>
                  <td>105</td>
              </tr>
              <tr>
                  <td>lagiphone</td>
                  <td>1</td>
                  <td>0</td>
                  <td>105</td>
              </tr>
              <tr>
                  <td>pohatu771</td>
                  <td>1</td>
                  <td>0</td>
                  <td>104</td>
              </tr>
          </tbody>
        </table>
        <p>
          This is a table of contributors in two time periods. A repeat value of 2 means that the user has been on the list twice.
        </p>
        <p>
          We can see from the table that only 5 usernames were on the list during the window period before and after iphone14 was released; the other users only existed in a single list.
        </p> 
        <p> 
          This shows that most of the contributors do not overlap. This shows that the same group of active contributors did not contribute content before and after the release of iPhone 14. The contributor pattern has changed dynamically. Obviously, the two groups of people have different interests in the iPhone.
        </p>  
        <p>
          We can infer that the release of iPhone 14 may have attracted users with more investment or interest in the new model, or there may have been many users who are not usually active, leading to changes in the contribution model.
        </p>
				
</section>
<section id="EDA-2" class="level2">
  <h2 class="anchored" data-anchor-id="EDA-2">Research on posts in iphone community (EDA 2)</h2>
  <p><strong>A Reminder for Our Business Goal:</strong>Conduct An in-depth exploration of popular posts on the iPhone Reddit subreddit, designed to provide users, forum moderators, and technology companies with effective recommendations so that they can better serve the interests and needs of the community, and potentially influence future product discussions. and development.  </p>
  <p><strong>Analysis:</strong>  
    <p>After conducting an in-depth study of active contributors, and to gain a deeper understanding of the patterns of the iPhone community, we took an in-depth look at the posting patterns of the iPhone Reddit subreddit, aiming to provide useful insights for users, moderators, and technology companies.</p>
    
    <p>The analysis focuses on two key periods in 2022, before and after the release of iPhone 14. The total number of posts is a very obvious sign. Changes in this number can easily explain the changes in community activity before and after the release of iPhone 14.</p>
    
    <p>The table below shows the total number of posts before and after the release of iPhone 14:</p>
    
  <table class="dataframe table table-sm table-striped">
    <tr>
        <th>Time Period</th>
        <th>Counts of Posts</th>
    </tr>
    <tr>
        <td>March to June</td>
        <td>3313</td>
    </tr>
    <tr>
        <td>August to December</td>
        <td>10302</td>
    </tr>
  </table>
    <p>The number of posts increased significantly from 3,313 between March and June to 10,302 between August and December, indicating a significant surge in community engagement following the iPhone 14 launch. This sharp rise may be attributed to the increased discussion and interest generated by the new release. Showing that product launches play a key role in driving user activity within the iPhone subreddit.</p>

    <p>After studying the insights brought by the total number of posts published, we can deeply explore the distribution of post scores and the number of comments to see what patterns exist in posts published during the two windows before and after the release of iPhone 14, that is their score and review count distribution.</p>

      <iframe src="../website/eda2_1.html" width="800" height="600"></iframe>
      <p>This scatter plot is the distribution of scores and number of comments for all posts published in the iPhone community from March to July 2022. The abscissa is the score, the ordinate is the number of comments.</p>

    <p>According to the observation on the scatter plot, the scores and number of comments of most posts are concentrated within 250 scores and 200 number of comments, and the origin has the most clustered points, which means that most posts do not score high and have fewer comments.</p>

    <p>In addition, the distribution of post scores and number of comments shows a positive correlation trend, indicating that the two complement each other and achieve each other. That is, posts with higher post scores generally attract more comments, and vice versa.</p>

    <p>There are very few outliers: for example, posts with very high scores but few comments, and posts with averages close to 400 but very low scores. For such abnormal posts, further analysis is needed to determine the reasons for their anomalies.</p>

      <iframe src="../website/eda2_2.html" width="800" height="600"></iframe>
      <p>This scatter plot is the distribution of scores and number of comments for all posts published in the iPhone community from August to December 2022. The abscissa is the score, the ordinate is the number of comments.</p>
  
      <p>According to the observation on the scatter chart, after the release of iPhone 14, the scores and number of comments of most posts are concentrated within 500 scores and 500 comments. Comparing the distribution chart of post scores and number of comments before the release of iPhone 14, it can be seen that the average number of posts The popularity has been significantly increased, which shows that the release of the new product iPhone14 has driven the activity of the community.</p>
      
      <p>
        When studying the word cloud composition before and after the release of iPhone 14, we can quickly discover the most popular topics and trends in the iPhone subsection.
      </p>
      <img src="../data/plots/word_cloud_1.png" alt="Image 3" style="max-width: 100%;">
        <p>
          This is a word cloud generated based on the title of the post before iPhone 14 was released.
        </p>
        <p>
          Highlighted words such as "battery", "issue", "photo", "data", "storage" and "camera" indicate that battery life, system issues, photo management, data security, storage space and camera quality are user concerns. There are no particularly prominent words about new product launches, indicating that user discussions have stabilized five months after the release of iPhone 13.
        </p>
      <img src="../data/plots/word_cloud_2.png" alt="Image 3" style="max-width: 100%;">
        <p>This is the word cloud generated based on the title of the post after iPhone14 was released.</p>
        <p>During this period, the fonts such as "Pro", "Max", and "new" became larger, indicating the release of the iPhone 14 series and the increase in related discussions. The prominence of words such as "video", "wallpaper", "iMessage", and "charging" may indicate discussions of new features or problems users are encountering on new devices.</p>
        <p>From the word cloud, we can find the most popular topics and trends in the "iPhone" subreddit, such as paying attention to battery life issues; storage management, choosing the mobile phone memory that best suits you; discussions about cameras, which can make users want to take pictures, and get good suggestions; in view of the frequent occurrence of words such as "issue" and "problem", users are advised to pay attention to check it to provide more useful purchasing suggestions.</p>
        <p>Overall, these two word clouds provide a macro perspective, showing the core topics that users care about. For users, they can quickly obtain the focus of the iPhone community on new products based on the composition of the word cloud, quickly read and obtain useful information, and help provide purchasing suggestions. For community managers and content creators, understanding these trends can help develop a content strategy that is more aligned with user needs. For product development teams, user discussion points can serve as feedback to improve existing products or guide the development of future products.</p>

</section>
<section id="EDA-3" class="level2">
    <h2 class="anchored" data-anchor-id="EDA-3">Reddit Impact Analysis (EDA 3)</h2>
    <p><strong>A Reminder for Our Business Goal:</strong> We aim to analyze the influence itself. Our primary goal in the Exploratory Data Analysis tasks is to understand and identify elements that hold significant influence or attract widespread attention across different communities. However, the question of what behaviors or outcomes can be deemed as having substantial impact remains to be explored. This is the topic we are about to delve into.</p>
    <p><strong>Analysis:</strong>  
    <iframe src="../website/eda3_scatter_plot_1.html" width="800" height="600"></iframe>
      <p>
        The above figure explores whether a post becomes instantly popular. We sorted the posts based on the number of comments and score. In cases where both the number of comments and score are higher, a shorter time_difference indicates a higher likelihood of the post becoming instantly popular. In other words, if a post receives a significant number of comments and scores in a short period, it may indicate that it has become instantly popular. Therefore, in our scatterplot results, a higher position, larger size, and a color closer to blue for the dots indicate that the post is more likely to become popular in the short term, exerting a significant influence in a brief period.
      </p>
      <iframe src="../website/eda3_scatter_plot_2.html" width="800" height="600"></iframe>
      <p>
        The above figure explores whether a post has persistent influence. We sorted the posts based on the time_difference. In cases where the time_difference is longer, a higher number of comments indicates a higher level of the post's sustained influence. In other words, we explore whether a post has a longer-lasting impact by tracking the timestamps of comments. Similarly, in our scatterplot results, a higher position, larger size, and a color closer to blue for the dots indicate that the post has a more persistent influence.
      </p>
      <p>
        We think that to explore influence, it is not only necessary to examine whether a post attracts significant attention in a short period (instant popularity) but also crucial to assess the sustained coverage of influence for the post. For example, based on the results of the two plots above, the post "Do you trust Apple with their views on privacy? or do you think its all fake?" not only attracted a significant amount of attention in a short period but also maintained high attention over an extended duration. In other words, this post has a substantial and lasting influence.
      </p>
      <p>

      </p>

</section>
</section>




</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Content 2023 by [Project Team 14] <br>This analysis uses ChatGPT to assist in fixing grammar and selecting vocabulary.</a></div>   
    <div class="nav-footer-right">Made with and <a href="https://quarto.org/">Quarto</a><br> <a href="https://github.com/gu-dsan6000/fall-2023-reddit-project-team-14">View the source at GitHub</a></div>
  </div>
</footer>



</body></html>